version: '3'
services:
  # influx_2.0:
  #   image: influxdb:2.0.4
  #   volumes:
  #     # Mount for influxdb data directory and configuration
  #     - influxdb-2-storage:/.influxdb-2-storage
  #     - ./influx_2.0/init.db/:/docker-entrypoint-initdb.d/
  #   ports:
  #     - "8086:8086"
  #   env_file:
  #     - ./influx_2.0/influxdb.env
  influx_1.8:
    image: influxdb:1.8.4
    volumes:
      - influxdb-1-storage:/.influxdb-1-storage
      - ./influx_1.8/init.db/:/docker-entrypoint-initdb.d/
    ports:
      - "8086:8086"
    env_file:
      - ./influx_1.8/influxdb.env
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/:/etc/grafana/provisioning
    depends_on:
      - influx_1.8
    env_file:
      - ./grafana/grafana.env
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influx_1.8
    env_file:
      - ./chronograf/chronograf.env
  node-cron:
    build: ./sensor_reader/
    network_mode: host
    privileged: true
volumes:
  influxdb-2-storage:
  influxdb-1-storage:
  grafana-storage:
  chronograf-storage: